'use client';

import { ForeignerAssistantOutput } from "@/ai/flows/foreigner-local-assistant-query";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { 
  ShieldCheck, AlertTriangle, Sparkles, Copy, 
  ArrowRight, Landmark, CheckCircle2 
} from "lucide-react";
import Link from "next/link";
import { useToast } from "@/hooks/use-toast";

interface AssistantResponseCardProps {
  result: ForeignerAssistantOutput;
  query: string;
  onFollowUp: (q: string) => void;
}

export function AssistantResponseCard({ result, query, onFollowUp }: AssistantResponseCardProps) {
  const { toast } = useToast();

  const copyToClipboard = () => {
    navigator.clipboard.writeText(result.answer);
    toast({
      title: "Copied!",
      description: "Response text copied to clipboard.",
    });
  };

  const confidenceStyles = {
    high: "bg-emerald-500/10 text-emerald-400 border-emerald-500/20",
    medium: "bg-orange-500/10 text-orange-400 border-orange-500/20",
    low: "bg-red-500/10 text-red-400 border-red-500/20",
  };

  return (
    <Card className="border-none shadow-2xl bg-white/5 rounded-3xl overflow-hidden animate-in fade-in slide-in-from-top-4 duration-500">
      <CardContent className="p-0">
        {/* Header */}
        <div className="px-8 py-6 border-b border-white/5 flex items-center justify-between bg-white/[0.02]">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-lg gradient-tanzania flex items-center justify-center">
              <Sparkles className="w-4 h-4 text-white" />
            </div>
            <div>
              <p className="text-[10px] font-black uppercase tracking-widest text-slate-500">Local Assistant Response</p>
              <p className="text-xs text-slate-300 font-bold line-clamp-1 italic">"{query}"</p>
            </div>
          </div>
          <Badge className={`h-7 rounded-full px-3 text-[10px] uppercase tracking-widest ${confidenceStyles[result.confidence]} border`}>
            {result.confidence === 'high' ? <ShieldCheck className="w-3 h-3 mr-1.5" /> : <AlertTriangle className="w-3 h-3 mr-1.5" />}
            {result.confidence} Confidence
          </Badge>
        </div>

        {/* Body */}
        <div className="p-8 space-y-8">
          <div className="prose prose-invert max-w-none">
            <p className="text-xl leading-relaxed text-slate-200 font-medium whitespace-pre-wrap">
              {result.answer}
            </p>
          </div>

          {/* Key Points */}
          {result.keyPoints && result.keyPoints.length > 0 && (
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {result.keyPoints.map((point, idx) => (
                <div key={idx} className="bg-primary/5 border border-primary/10 p-4 rounded-2xl flex gap-3">
                  <CheckCircle2 className="w-5 h-5 text-primary shrink-0 mt-0.5" />
                  <p className="text-sm font-medium text-slate-300">{point}</p>
                </div>
              ))}
            </div>
          )}

          {/* Low Confidence Warning */}
          {result.confidence !== 'high' && (
            <div className="p-4 rounded-2xl bg-orange-500/5 border border-orange-500/20 flex gap-3 items-center">
              <AlertTriangle className="w-5 h-5 text-orange-400 shrink-0" />
              <p className="text-xs text-orange-200/70 font-medium">
                This answer is generated by AI and should be verified with official Tanzanian authorities or sector regulators.
              </p>
            </div>
          )}

          {/* Bottom Actions & Related */}
          <div className="pt-6 border-t border-white/5 flex flex-col md:flex-row md:items-center justify-between gap-6">
            {result.relatedSectors.length > 0 && (
              <div className="flex flex-wrap items-center gap-3">
                <span className="text-[10px] uppercase font-black tracking-widest text-slate-500 flex items-center gap-2">
                  <Landmark className="w-3 h-3" /> Related Guides:
                </span>
                <div className="flex flex-wrap gap-2">
                  {result.relatedSectors.map(s => (
                    <Link key={s} href={`/${s.toLowerCase().replace(/ & /g, '-').replace(/ /g, '-')}`}>
                      <Badge variant="secondary" className="bg-primary/20 text-primary border-primary/20 px-3 py-1 text-[10px] uppercase font-bold hover:bg-primary hover:text-white transition-colors cursor-pointer">
                        {s}
                      </Badge>
                    </Link>
                  ))}
                </div>
              </div>
            )}
            <Button variant="ghost" size="sm" onClick={copyToClipboard} className="text-slate-400 hover:text-white gap-2 rounded-xl">
              <Copy className="w-4 h-4" /> Copy Answer
            </Button>
          </div>
        </div>

        {/* Follow-ups */}
        {result.followUpQuestions && result.followUpQuestions.length > 0 && (
          <div className="bg-white/[0.03] p-8 border-t border-white/5 space-y-4">
            <p className="text-[10px] uppercase font-black tracking-widest text-slate-500">Explore Further</p>
            <div className="flex flex-wrap gap-2">
              {result.followUpQuestions.map((q, idx) => (
                <button 
                  key={idx} 
                  onClick={() => onFollowUp(q)}
                  className="px-4 py-2 rounded-xl bg-white/5 border border-white/5 text-xs font-bold text-slate-300 hover:bg-primary/20 hover:border-primary/40 transition-all flex items-center gap-2 group"
                >
                  {q} <ArrowRight className="w-3 h-3 opacity-0 group-hover:opacity-100 transition-opacity" />
                </button>
              ))}
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
